<?php
/**
 * Created by PhpStorm.
 * User: mike
 * Date: 7/13/16
 * Time: 10:50 PM
 */

namespace App\Classes;


class EventfulEvents extends EventfulRestClient
{

    public $method = 'events';
    
    public function __call($name, $arguments)
    {
        parent::__call($name, $arguments); // TODO: Change the autogenerated stub
        
        $this->xml = collect(collect($this->xml)->get('events'))->get('event');

        return $this;
    }
}